CinelWeb/Controllers/InscritosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CinelWeb.Models;

namespace CinelWeb.Controllers
{
    public class InscritosController : Controller
    {
        DCinscricoesDataContext dc = new DCinscricoesDataContext();

        // GET: Contatos
        public ActionResult Index()
        {
            return View(dc.Inscritos);
        }

        // POST: Contatos/Create
        [HttpPost]
        public ActionResult Inscricao(Inscrito novaInscricao)
        {
            if (ModelState.IsValid)
            {
                dc.Inscritos.InsertOnSubmit(novaInscricao);
            }
            try
            {
                dc.SubmitChanges();
                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

CinelWeb/Views/Shared/_Layout.cshtml
@model CinelWeb.Models.Inscrito

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="Description" content="formação e investigação na área da eletrónica">
    <meta name="Keywords" content="formação, ensino profissional, programação, automação, robótica, telecomunicações, investigação em eletrónica">
    <meta name="author" content="cet 30">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Cinel - @ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
</head> 

<body>

    @RenderBody()

    <footer>
        <p>CINEL Todos os direitos reservados &copy;@DateTime.Now.Year</p>
    </footer>

    <!---Janela modal--->
    <div id="abre-janela" class="w3-modal">
        <div class="w3-modal-content">

            <header class="w3-container w3-red">
                <span onClick="document.getElementById('abre-janela').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                <h2>Inscrição</h2>
            </header>
            <div class="w3-container">
                @using (Html.BeginForm("Inscricao", "Inscritos", FormMethod.Post))
                 {
                <div class="w3-section">
                    <div class="w3-input w3-border w3-margin-bottom">
                        @Html.EditorFor(model => model.nome, new { htmlAttributes = new { type = "text", placeholder = "Nome" } })
                    </div>
                    <div class="w3-input w3-border w3-margin-bottom">
                        @Html.EditorFor(model => model.utilizador, new { htmlAttributes = new { type = "text", placeholder = "Utilizador" } })
                    </div>
                    <div class="w3-input w3-border w3-margin-bottom">
                        @Html.EditorFor(model => model.dataInscricao, new { htmlAttributes = new { type = "text", placeholder = "Data" } })
                    </div>
                    <div class="w3-input w3-border w3-margin-bottom">
                        @Html.EditorFor(model => model.senha, new { htmlAttributes = new { id = "senha", type = "password", placeholder = "Senha" } })
                    </div>


                    <label>Confirmar Senha</label>
                    <input oninput="ConfirmarSenha(this)" class="w3-input w3-border w3-margin-bottom" type="password" placeholder="Confirme a senha">
                    <label id="erro" class="w3-hide">As senhas não coincidem</label>
                    <button id="validar" class="w3-black w3-btn-block w3-section w3-padding" type="submit">Enviar</button>
                </div>
                 }
             </div>
        </div>
    </div>

    <script src="../Scripts/script.js"></script>

</body>

</html>